Feature : Add counter [fixes #27]
eduardconstantin/Comic-book-button-anim pull request #32
Opened 2022-10-14 17:46 UTC by najeebkp

Feature : Add counter [fixes #27]

## Description
Created a counter component, which will increase when button click happens.

[fixes #27]

Closes #27

## How Has This Been Tested?
Manually tested

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes. They do not dramatically decrease the test coverage metric
- [x] All new and existing tests passed.
- [x] I give my permission for my code to be used in this project under this license and any future license terms

2022-10-14 18:09 UTC, eduardconstantin requested changes

2022-10-14 18:09 UTC, eduardconstantin commented on src/App.tsx
> +          focusBtnName="FOCUS"
Please remove the focus prop

2022-10-14 18:09 UTC, eduardconstantin commented on src/components/ComicButton/ComicButton.tsx
> +  focusBtnName,
remove the prop

2022-10-14 18:09 UTC, eduardconstantin commented on src/components/ComicButton/ComicButton.tsx
> +  focusBtnName: string;
Remove focus

2022-10-14 18:09 UTC, eduardconstantin commented on src/App.tsx
> +import React from "react";
```suggestion
import React, { useState } from "react";
```

2022-10-14 18:09 UTC, eduardconstantin commented on src/App.tsx
> +  const [count, setCount] = React.useState<number>(0);
```suggestion
  const [count, setCount] = useState<number>(0);
```

2022-10-14 18:09 UTC, eduardconstantin commented on src/components/Counter/Counter.tsx
> +      <div className={style.counter}>Count : {count}</div>
```suggestion
      <div className={style.counter}>Count - {count}</div>
```

2022-10-15 02:15 UTC, najeebkp commented
Changes made!

2022-10-15 09:55 UTC, eduardconstantin approved these changes

2022-10-15 09:56 UTC, eduardconstantin commented
Thank you! Don't forget to star the repo.

2022-10-15 09:56 UTC, eduardconstantin commented
@all-contributors please add @najeebkp for code

2022-10-15 09:56 UTC, merged